# Generated by Django 4.2.5 on 2023-11-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmileSphereApp', '0002_usertable_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_specialty', models.CharField(max_length=100)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('surgeon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surgeon_specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('surgeon_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
