# Generated by Django 5.0.2 on 2024-02-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmileSphereApp', '0006_alter_superadmin_email_alter_superadmin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='email',
            field=models.EmailField(default='admin@admin.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='password',
            field=models.CharField(default='admin123', max_length=100),
        ),
    ]
