# Generated by Django 4.2.5 on 2024-03-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmileSphereApp', '0012_remove_clinic_latitude_remove_clinic_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='password',
            field=models.CharField(default='default_value_here', max_length=100),
        ),
    ]
